### ISSUE TITLE
Tensors of the same index must be on the same device and the same dtype except `step` tensors that can be CPU and float32 notwithstanding

### ISSUE THREAD

**Issue by yvKleinBottle** [thaipduong/LieGroupHamDL#2]
Hello, I will report this "--float = 64"error after modifying the "Tensors of the same index must be on the same device and the same dtype except `step` tensors that can be CPU and float32 notwithstanding"parameter. Excuse me, how to modify it?
The version of the library I use is pytorch 2.1.1+cu118，python3.9.5.

**Comment by thaipduong** [comment]
I haven't seen this error. Can you please provide more details? Which scripts did you run? And what did you change? Thanks.

**Comment by yvKleinBottle** [comment]
For pendulum/train _ pend _ SO3 _ friction program, the library I use is --float = 64, device = cuda:0, python3.9.5, torch 2.1.1+cu118, torchdiffeq 0.2.3, gym 0.26.2, numpy 1.24.4, scipy 1.11.4, matplotlib 3.8.2, pyglet 1.5.27
<img width="997" alt="PixPin_2024-07-04_08-47-27" src="https://github.com/thaipduong/LieGroupHamDL/assets/56949361/3ee0499f-0cd3-4961-9dea-a9470445881a">

**Comment by yvKleinBottle** [comment]
<img width="1001" alt="PixPin_2024-07-04_08-57-54" src="https://github.com/thaipduong/LieGroupHamDL/assets/56949361/61e92966-79c4-4aa9-8ac2-cc1c4d103121">

**Comment by thaipduong** [comment]
Hi,
It looks like there is a pytorch bug in version 2.1.1: https://discuss.pytorch.org/t/tensors-of-the-same-index-must-be-on-the-same-device-and-the-same-dtype-except-step-tensors-that-can-be-cpu-and-float32-notwithstanding/190335. 

Please install another version or switch to float32.

**Comment by yvKleinBottle** [comment]
Ok, thank you.
